### PR TITLE
Fix url not showing in questions detail and add success/error handlers

### LINKED ISSUE #12: Reference URL not showing in questions detail
`url` is not shown anywhere

### PR DESCRIPTION
**Pull request by njxue**
Resolves #12

### CODE REVIEW

File: frontend/src/presentation/pages/QuestionsPage.tsx [hunk 1]
```diff
@@ -177,7 +187,12 @@ const QuestionsPage: React.FC = () => {
                 footer={null}
                 width={1200}
             >
-                <NewQuestionForm />
+                <NewQuestionForm
+                    onSubmit={() => {
+                        handleCloseModal();
+                        fetchQuestions();
```
Comment (Nephelite) [inline frontend/src/presentation/pages/QuestionsPage.tsx:193]: No need to fetch all questions when submitted.

**Review by Nephelite — APPROVED** [review]
LGTM, but I will fix the unnecessary fetchQuestions if you dw to.

File: frontend/src/presentation/pages/QuestionsPage.tsx (hunk 1 above)
Comment (njxue) [reply frontend/src/presentation/pages/QuestionsPage.tsx:193]: Ill fix it in a later PR
